# Dev 分支推送部署预览
## 仅部署 Win 端
name: Build Dev

on:
  push:
    branches:
      - dev
      - master

jobs:
  release:
    name: Build Website
    runs-on: ubuntu-latest

    steps:
      # 检出 Git 仓库
      - name: Check out git repository
        uses: actions/checkout@v4.1.1
      # 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "18.x"
      # 设置 AMap API Key
      - name: Set AMap API Key
        run: sed -i 's/Example/${{ secrets.AMAP_API_KEY }}/g' .env
      # 安装项目依赖
      - name: Install Dependencies
        run: npm install
      # 构建程序
      - name: Build Website
        run: npm run build
      - name: Deploy To tar
        run: tar -cvf dist.tar ./dist
      - name: Zip the Build
      - name: Create Release and Upload Release Asset
          uses: softprops/action-gh-release@v2
          if: startsWith(github.ref, 'refs/tags/')
          with:
            tag_name: ${{ github.ref }}
            name: Release ${{ github.ref }}
            body: TODO New Release.
            draft: false
            prerelease: false
            files: |
              ${{ secrets.ReleaseZipName }}.zip
              LICENSE 
